# Generated by Django 3.1 on 2024-02-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
        ('category', '0002_alter_category_options'),
    ]

    operations = [
    ]
